### ISSUE TITLE
Q: Stuctural Issue

### ISSUE THREAD

**Issue by modellking** [derElias/udvide-Server#33]
Vuforia WebService doesn't allow to send an update for a target if the target is still processing.
* This means we can't just send the update of the meta-package (and activeFlag) to VWS in the synchronous php instance, because it could take as long as 10 minutes to receive an answer if we wait for it.

* The second option is an asynchronous Worker, which can be done using a framework ("Gearman" seems to be the market leader, and looks very cool) or by writing the worker ourselves.

* The third option is to change how we planned to realize our data-structure and giving up on ACID-principles by generating a second target id on our end and updating the database after the data creation

Other ideas? Opinions?

**Comment by LuZi4** [comment]
imho implementing a worker should be the preferred way. That's because it do not harm the database standards and give us the opportunity to implement an additional task, mixing up with a topic from pvs, which would be nice to have in the doku. 
On the other side of the coin generating a second target id seems to be the faster way to get a working overall system. Maybe we should start with the last option.

**Comment by modellking** [comment]
after discussion we concluded that we should go the easy to implement way, the additional target identifier, first and maybe take a more refined approach later down the line
